version: '3'

networks:
  network_prod:
    driver: bridge

services:

  postgresql:
    build:
      context: ./tr-postgresql
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_USER_ADMIN: ${DB_USER_ADMIN}
        DB_PASSWORD_ADMIN: ${DB_PASSWORD_ADMIN}
        DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - network_prod

  tr-nestjs:
    container_name: tr-nestjs
    image: tr-nestjs
    build:
      context: ./tr-nestjs
      args:
        DB_HOST: ${DB_HOST}
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_USER_ADMIN: ${DB_USER_ADMIN}
        DB_PASSWORD_ADMIN: ${DB_PASSWORD_ADMIN}
        DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        MAIL_HOST: ${MAIL_HOST}
        MAIL_PORT: ${MAIL_PORT}
        MAIL_USER: ${MAIL_USER}
        MAIL_PASS: ${MAIL_PASS}
        CLIENT_ID: ${CLIENT_ID}
        CLIENT_SECRET: ${CLIENT_SECRET}
    restart: always
    env_file:
      - ./.env
    ports:
      - 8000:8000
    networks:
      - network_prod
    depends_on:
      - postgresql  # Ajout de la dépendance explicite
